// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pzffdyeccomsebvpjbfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6ZmZkeWVjY29tc2VidnBqYmZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NjY4NzgsImV4cCI6MjA5MDA0Mjg3OH0.33SMBD-jzt92vJ0hhtpA3m0MtTKDijGzCsAtSimPrY8";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);